# Configuration file in YAML format

# Dataset settings
NUM_CYCLES: 7
NUM_PREDS: 7
FEATURE_DIM1: 16
FEATURE_DIM2: 16
NUM_ATTENTION: 16

# Training settings
EPOCHS: 1000
LEARNING_RATE: 0.001

# Other settings
BATCH_SIZE: 32
USE_GPU: True
FEATURE_DIM: 4
